name: osu_course_review
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
